title:              Jewish Book Finds
email:              jewishbookfinds1@gmail.com
description:        A blog about (old) jewish books 
author:             Jewish Book Finds
baseurl:            "/"
url:                "https://israeldav.github.io"
root:               "/"

# Social Profiles
twitter_username:   jewishbookfinds
#github_username:    StartBootstrap
#facebook_username:  StartBootstrap
instagram_username:  jewishbookfinds
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-178894389-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
